### ISSUE TITLE
improve popup style

### ISSUE THREAD

**Issue by a96lex** [martinezpl/owlie-yt-addon#26]
Open for discussion.

Recently, on #25, we removed the kofi iframe.

However the new popup feels lacking to me. I would do it a bit more visual with thes changes:

- add copy functionality: when user clicks on the code, or clicks on a `copy id` button, that is aligned left opposite to the `regenerate code`. I am not sure if this needs clipboard permissions, it is a point to take into account.
- add tutorial for kofi donations: this could consist on an image with an arrow pointing to the field where the user needs to paste their code into. I would put a button to copy code and another to `go to kofi` taking up as muych horizontal space as possible.
- remove lock. User should never be able to edit the field. Maybe if they click it, we can also copy it.
- add indicator after the user has copied the field. smt like a popup that lives for a couple seconds

"mockup":
![image](https://user-images.githubusercontent.com/62766970/218776595-89c07f24-ba4f-4e0a-832a-396e5a89b753.png)

**Comment by a96lex** [comment]
what do you think @martinezpl

**Comment by martinezpl** [comment]
I like it! Just one reservation about the code field.

The code is synced into the browser profile, fine, but let's say a user migrates to another browser/PC having questions topped on his code. They should have a way to reuse this code, hence the lock

Btw we should ponder moving away from Ko-Fi to Stripe directly. We can then forget this clunky copy-paste workaround. Their devs were interested in adding custom parameters to their webhooks but haven't heard from them since.
